export const DOCUMENT_TYPES=["Chit Poster","Chit Plan","Month-wise Schedule","Auction Plan","Promotional Plan","Daily Collection Plan","Multi-plan Comparison","Rules Sheet","Terms and Conditions","Member Sheet","Receipt","Ledger","Custom/Unknown Chit Document"];
export const REVIEW_STATUS={VERIFIED:"Verified",PROBABLE:"Probable",NEEDS_REVIEW:"Needs Review",MISSING:"Missing",CUSTOM:"Custom Values",REJECTED:"Rejected"};
const FIELD_ALIASES={chitName:["chitname","chit_name","name"],chitValue:["chitvalue","chit_value","value"],memberCount:["membercount","members","total_members"],duration:["duration","months","total_months"],monthlyPayment:["monthlypayment","monthly_amount","installment","payment"],commission:["commission","commission_rate"]};
export const ChitDocumentUnderstandingEngine={
  validateFile(file){if(!file)return{valid:false,errors:["Choose a document to continue."]};const extension=file.name.split(".").pop()?.toLowerCase();const supported=["jpg","jpeg","png","webp","pdf","csv","json","xlsx","xls"];const errors=[];if(!supported.includes(extension))errors.push("Unsupported file type. Use image, PDF, CSV, Excel or JSON.");if(Number(file.size||0)>15*1024*1024)errors.push("File exceeds the 15 MB safety limit.");return{valid:errors.length===0,errors,extension,requiresExternalProvider:["jpg","jpeg","png","webp","pdf"].includes(extension),requiresSpreadsheetProvider:["xlsx","xls"].includes(extension)}},
  classify({fileName="",rawText=""}={}){const text=`${fileName} ${rawText}`.toLowerCase();const rules=[["receipt","Receipt"],["ledger","Ledger"],["member","Member Sheet"],["terms","Terms and Conditions"],["rule","Rules Sheet"],["comparison","Multi-plan Comparison"],["daily","Daily Collection Plan"],["auction","Auction Plan"],["poster","Chit Poster"],["schedule","Month-wise Schedule"],["plan","Chit Plan"],["promo","Promotional Plan"]];return rules.find(([word])=>text.includes(word))?.[1]||"Custom/Unknown Chit Document"},
  buildAnalysis({file,rawText="",rows=[],provider="manual"}={}){const normalizedRows=rows.map(normalizeScheduleRow);const fields=extractFields(rawText,normalizedRows);const classification=this.classify({fileName:file?.name,rawText});const relationships=this.detectRelationships(normalizedRows);const missing=Object.entries(fields).filter(([,field])=>!field.normalizedValue).map(([key])=>key);return{id:`analysis-${Date.now()}`,status:"Needs Review",originalDocument:{name:file?.name||"Manual entry",type:file?.type||"text/manual",size:file?.size||0,lastModified:file?.lastModified||null},rawExtractedContent:rawText,documentType:classification,chitModel:relationships.length?"Month-wise configured":"Unconfirmed",fields,schedule:normalizedRows,rules:[],terms:[],relationships,missingInformation:missing,clarificationQuestions:missing.map(key=>`Please confirm ${humanize(key)}.`),userCorrections:[],confirmedConfiguration:null,auditHistory:[audit("ANALYSIS_CREATED",{provider,classification})],provider}},
  detectRelationships(rows=[]){if(rows.length<2)return[];return ["standardPayment","nonLiftedPayment","liftedPayment","prizeAmount","bidAmount","dividendPerMember","commissionValue"].map(field=>verifyConstant(rows,field)).filter(Boolean)},
  applyCorrections(analysis,corrections={}){const fields={...analysis.fields};Object.entries(corrections.fields||{}).forEach(([key,value])=>{fields[key]={...(fields[key]||fieldRecord("",0,"Missing")),userCorrectedValue:value,normalizedValue:normalizeValue(key,value),status:value?"Verified":"Missing",confidence:value?1:0}});const schedule=(corrections.schedule||analysis.schedule).map(normalizeScheduleRow);return{...analysis,fields,schedule,rules:corrections.rules||analysis.rules,terms:corrections.terms||analysis.terms,relationships:this.detectRelationships(schedule),missingInformation:Object.entries(fields).filter(([,field])=>!field.normalizedValue).map(([key])=>key),userCorrections:[...analysis.userCorrections,{at:new Date().toISOString(),corrections}],auditHistory:[...analysis.auditHistory,audit("USER_CORRECTION",{fields:Object.keys(corrections.fields||{})})]}}
};
function extractFields(rawText,rows){let source={};try{source=JSON.parse(rawText||"{}");if(Array.isArray(source))source={}}catch{source={}}const normalizedSource=Object.fromEntries(Object.entries(source).map(([key,value])=>[key.toLowerCase().replace(/[^a-z0-9]/g,""),value]));const first=rows[0]||{};return Object.fromEntries(Object.entries(FIELD_ALIASES).map(([key,aliases])=>{const raw=aliases.map(alias=>normalizedSource[alias.toLowerCase().replace(/[^a-z0-9]/g,"")]).find(v=>v!==undefined)??(key==="monthlyPayment"?first.standardPayment:"");return[key,fieldRecord(normalizeValue(key,raw),raw?0.85:0,raw?"Probable":"Missing",`Document field: ${aliases[0]}`)]}))}
function fieldRecord(value,confidence,status,evidence="Manual review"){return{originalValue:value,normalizedValue:value,userCorrectedValue:null,confidence,status,evidence}}
function normalizeValue(key,value){return key==="chitName"?String(value||"").trim():Number(String(value||"").replace(/[^\d.-]/g,""))||0}
function normalizeScheduleRow(row,index=0){return{...row,monthNumber:Number(row.monthNumber||row.month||index+1),monthLabel:row.monthLabel||`Month ${Number(row.monthNumber||row.month||index+1)}`,standardPayment:Number(row.standardPayment||row.payment||row.monthlyPayment||0),nonLiftedPayment:Number(row.nonLiftedPayment||row.non_lifted_payment||row.payment||0),liftedPayment:Number(row.liftedPayment||row.lifted_payment||row.payment||0),prizeAmount:Number(row.prizeAmount||row.prize||0),bidAmount:Number(row.bidAmount||row.bid||0),dividendPerMember:Number(row.dividendPerMember||row.dividend||0),commissionValue:Number(row.commissionValue||row.commission||0),status:row.status||"Needs Review",confidence:Number(row.confidence||0.6),evidence:row.evidence||`Imported row ${index+1}`,isUserConfirmed:Boolean(row.isUserConfirmed)}}
function verifyConstant(rows,field){const applicable=rows.filter(row=>Number.isFinite(Number(row[field])));if(!applicable.length)return null;const values=applicable.map(row=>Number(row[field]));const first=values[0];const matches=values.filter(value=>value===first).length;const ratio=matches/values.length;return{field,type:ratio===1?"Fixed relationship":"Custom month-wise values",value:ratio===1?first:null,matchedRows:matches,totalRows:values.length,status:ratio===1?"Verified":ratio>=.7?"Probable":"Custom Values",confidence:ratio,evidence:`Tested ${values.length} applicable rows`}}
function humanize(key){return key.replace(/([A-Z])/g," $1").toLowerCase()}
function audit(action,details){return{action,details,at:new Date().toISOString()}}
