import { LocalRuleProvider } from "./providers/LocalRuleProvider.js";

const REQUIRED_FIELDS = [
  ["chitValue", "What is the target chit value?"],
  ["members", "How many members will join?"],
  ["duration", "How many months should the chit run?"],
  ["auctionRequired", "Is auction required?"],
  ["luckyDrawRequired", "Is lucky draw required?"],
  ["liftEffectiveRule", "After lifting, should the new payment start same month or next month?"],
  ["commissionValue", "What commission percentage or value should apply?"],
  ["riskPreference", "Risk preference: SAFE, BALANCED, or GROWTH?"],
];

export const AIConversationSetup = {
  start(text = "", activeTenantContext = {}) {
    const collectedFields = parseInitialText(text);
    return buildState({ activeTenantContext, intent: "CHIT_SETUP", collectedFields });
  },

  answer(state, answer) {
    const field = state.missingFields[0];
    const collectedFields = { ...state.collectedFields, [field]: normalizeAnswer(field, answer) };
    return buildState({ ...state, collectedFields });
  },
};

function buildState({ activeTenantContext = {}, intent, collectedFields = {}, sessionId } = {}) {
  const missingFields = REQUIRED_FIELDS.map(([field]) => field).filter((field) => collectedFields[field] === undefined || collectedFields[field] === "");
  const completed = missingFields.length === 0;
  const draftPlan = completed ? LocalRuleProvider.designProposals(collectedFields) : null;
  return {
    sessionId: sessionId || `conversation-${Date.now()}`,
    tenantId: activeTenantContext.tenant_id || "",
    intent,
    collectedFields,
    missingFields,
    assumptions: completed ? ["Generated by local structured conversation. Owner review required."] : [],
    currentQuestion: completed ? "Review the generated schedule and confirm." : REQUIRED_FIELDS.find(([field]) => field === missingFields[0])?.[1] || "",
    completed,
    draftPlan,
  };
}

function parseInitialText(text) {
  const normalized = String(text || "").toLowerCase();
  const lakhMatch = normalized.match(/(\d+(?:\.\d+)?)\s*lakh/);
  const memberMatch = normalized.match(/(\d+)\s*members?/);
  return {
    ...(lakhMatch ? { chitValue: Number(lakhMatch[1]) * 100000 } : {}),
    ...(memberMatch ? { members: Number(memberMatch[1]) } : {}),
  };
}

function normalizeAnswer(field, answer) {
  if (["chitValue", "members", "duration", "commissionValue"].includes(field)) {
    return Number(String(answer || "").replace(/[^\d.]/g, "")) || 0;
  }
  if (["auctionRequired", "luckyDrawRequired"].includes(field)) {
    return /yes|true|required|need/i.test(String(answer));
  }
  return answer;
}
