import { useRef, useState } from "react";
import { AlertTriangle, Bot, Camera, Check, ChevronRight, FileSpreadsheet, FileText, HelpCircle, Image, Mic, Paperclip, ReceiptText, Send, X } from "lucide-react";
import { useNavigate } from "react-router-dom";
import ChitLayout from "../../components/chit/ChitLayout";
import { useAuth } from "../../hooks/useAuth";
import { aiOrchestrator } from "../../services/ai/AIOrchestrator";
import "./AIWorkspace.css";

const CHIPS=["Show pending","Today's collection","Generate receipt","Open reports","Calculate monthly profit","Create a new chit"];
const ACCEPTED=["image/jpeg","image/png","image/webp","application/pdf","text/csv","application/json","application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"];
function AIWorkspace(){
  const navigate=useNavigate(); const {activeTenantContext,permissions}=useAuth(); const fileRef=useRef(null);
  const [text,setText]=useState(""); const [attachments,setAttachments]=useState([]); const [messages,setMessages]=useState([]); const [busy,setBusy]=useState(false);
  const providers=aiOrchestrator.getProviderStatus();
  function addFiles(files){const next=[...files].map(file=>validateFile(file));setAttachments((current)=>[...current,...next].slice(0,8));}
  function submit(value=text,confirmed=false){const input=String(value||"").trim();if(!input&&!attachments.length)return;setBusy(true);setMessages((items)=>[...items,{id:crypto.randomUUID(),kind:"request",text:input||"Review attached files",attachments}]);window.setTimeout(()=>{const result=aiOrchestrator.route({text:input||"Read chit pattern from image",tenantContext:activeTenantContext,permissions,confirmed});setMessages((items)=>[...items,{id:crypto.randomUUID(),kind:"response",input,result}]);setBusy(false);setText("");setAttachments([])},220)}
  return <ChitLayout title="VARDHAN AI" subtitle="One secure conversation workspace for every MITRA NIDHI workflow"><div className="ai-workspace">
    <aside className="ai-workspace-side"><div className="ai-side-brand"><Bot/><div><strong>Business copilot</strong><small>Tenant-aware and confirmation-safe</small></div></div><h3>Quick actions</h3>{CHIPS.map(chip=><button key={chip} onClick={()=>submit(chip)}>{chip}<ChevronRight size={15}/></button>)}<div className="ai-provider-list"><h3>Provider status</h3>{Object.entries(providers).map(([key,value])=><div key={key}><span>{key.toUpperCase()}</span><b className={value.configured?"ready":"offline"}>{value.configured?"Connected":"Not configured"}</b></div>)}</div></aside>
    <section className="ai-conversation"><header><div><span>Current workspace</span><strong>{activeTenantContext?.workspace_label||activeTenantContext?.tenant_id||"No workspace selected"}</strong></div><button onClick={()=>navigate("/chits/support")}><HelpCircle size={17}/> Support</button></header>
      <div className="ai-message-stream">{messages.length===0&&<WelcomeCard onAction={submit}/>} {messages.map(message=>message.kind==="request"?<RequestCard key={message.id} message={message}/>:<ResponseCard key={message.id} message={message} onNavigate={navigate} onConfirm={()=>submit(message.input,true)}/>)}{busy&&<div className="ai-thinking" role="status"><Bot/><span><b>Understanding your request</b><small>Checking tenant scope, permissions and safe local actions…</small></span><i/><i/><i/></div>}</div>
      {attachments.length>0&&<div className="ai-attachment-tray">{attachments.map((item,index)=><div key={`${item.file.name}-${index}`} className={item.error?"invalid":""}>{iconFor(item.file)}<span><strong>{item.file.name}</strong><small>{item.error||formatBytes(item.file.size)}</small></span><button onClick={()=>setAttachments(list=>list.filter((_,i)=>i!==index))}><X size={15}/></button></div>)}</div>}
      <footer className="ai-composer"><textarea value={text} onChange={e=>setText(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();submit()}}} placeholder="Ask in simple language — English, Telugu or mixed language"/><div><input ref={fileRef} type="file" multiple hidden accept=".jpg,.jpeg,.png,.webp,.pdf,.csv,.xlsx,.json" onChange={e=>addFiles(e.target.files)}/><button title="Attach file" onClick={()=>fileRef.current?.click()}><Paperclip/></button><button title="Camera or image" onClick={()=>fileRef.current?.click()}><Camera/></button><button title="Voice input" onClick={()=>setMessages(items=>[...items,{id:crypto.randomUUID(),kind:"response",result:{title:"Voice input is ready for provider connection",message:"No recording was created because the speech provider is not configured.",status:"needs_review",confidence:1,source:"Speech provider status",support:{route:"/chits/support"}}}])}><Mic/></button><button className="send" disabled={busy||(!text.trim()&&!attachments.length)||attachments.some(x=>x.error)} onClick={()=>submit()}><Send/> Send</button></div></footer>
    </section></div></ChitLayout>;
}
function WelcomeCard({onAction}){return <div className="ai-welcome-card"><Bot size={28}/><h2>What would you like to complete?</h2><p>I can explain calculations, open a workflow, review a file, prepare a receipt action, or show repository-backed business information.</p><div>{CHIPS.slice(0,4).map(x=><button key={x} onClick={()=>onAction(x)}>{x}</button>)}</div></div>}
function RequestCard({message}){return <article className="ai-request-card"><strong>You</strong><p>{message.text}</p>{message.attachments?.map(x=><span key={x.file.name}>{iconFor(x.file)} {x.file.name}</span>)}</article>}
function ResponseCard({message,onNavigate,onConfirm}){const r=message.result;return <article className={`ai-response-card status-${r.status}`}><header><Bot/><div><span>VARDHAN AI</span><h3>{r.title}</h3></div><Confidence value={r.confidence}/></header><section className="ai-answer-section"><span>Answer</span><p className="ai-simple-answer">{r.message}</p></section><section className="ai-answer-section"><span>Explanation and evidence</span><div className="ai-evidence-grid"><div><span>Source</span><strong>{r.source||"Local orchestration"}</strong></div><div><span>Safety status</span><strong>{r.requiresConfirmation?"Waiting for confirmation":"No protected change made"}</strong></div></div></section><StructuredPreview input={message.input} onNavigate={onNavigate}/>{r.warnings?.map(w=><div className="ai-warning" key={w}><AlertTriangle/>{w}</div>)}<div className="ai-response-actions">{r.requiresConfirmation&&<button className="confirm" onClick={onConfirm}><Check/>Confirm action</button>}{r.action?.route&&<button onClick={()=>onNavigate(r.action.route)}>{r.action.label||"Open workflow"}<ChevronRight/></button>}<button onClick={()=>onNavigate("/chits/academy")}><FileText/>Related guide and video</button><button onClick={()=>onNavigate(r.support?.route||"/chits/support")}><HelpCircle/>Support</button></div></article>}
function StructuredPreview({input="",onNavigate}){const [draft,setDraft]=useState({name:"",amount:"",members:""});const lower=input.toLowerCase();if(lower.includes("create")&&lower.includes("chit"))return <div className="ai-inline-form"><h4>Editable chit request</h4><div><label>Chit name<input value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})}/></label><label>Value<input value={draft.amount} onChange={e=>setDraft({...draft,amount:e.target.value})}/></label><label>Members<input value={draft.members} onChange={e=>setDraft({...draft,members:e.target.value})}/></label></div><small>This draft is not saved until reviewed in Chit Groups.</small></div>;if(lower.includes("receipt"))return <div className="ai-preview-card"><ReceiptText/><div><span>Receipt preview</span><strong>Uses the selected collection record</strong><small>No receipt was generated by this preview.</small></div><button onClick={()=>onNavigate("/chits/receipts")}>Select record</button></div>;if(lower.includes("report")||lower.includes("collection"))return <div className="ai-preview-table"><div><strong>Report preview</strong><small>Repository values load in Reports</small></div><table><thead><tr><th>Field</th><th>Source</th></tr></thead><tbody><tr><td>Period and filters</td><td>Reports workflow</td></tr><tr><td>Totals</td><td>Central calculation services</td></tr></tbody></table></div>;return null}
function Confidence({value=0}){const percent=Math.round(value*100);return <span className={`ai-confidence ${percent>=80?"high":percent>=55?"medium":"low"}`}>{percent}% confidence</span>}
function validateFile(file){if(!ACCEPTED.includes(file.type)&&!file.name.toLowerCase().endsWith(".xlsx"))return{file,error:"Unsupported file type. Use image, PDF, CSV, Excel or JSON."};if(file.size>15*1024*1024)return{file,error:"File is larger than the 15 MB safety limit."};return{file,error:null}}
function iconFor(file){if(file.type.startsWith("image/"))return <Image size={17}/>;if(file.name.endsWith(".csv")||file.name.endsWith(".xlsx"))return <FileSpreadsheet size={17}/>;return <FileText size={17}/>}
function formatBytes(bytes){return bytes<1024*1024?`${Math.ceil(bytes/1024)} KB`:`${(bytes/1024/1024).toFixed(1)} MB`}
export default AIWorkspace;
