import { useEffect, useMemo, useState } from "react";
import { useNavigate } from "react-router-dom";
import { AlertTriangle, ArrowRight, Bell, Bot, CalendarDays, CircleHelp, FileText, Landmark, Plus, ReceiptText, Search, Sparkles, Target, Users, WalletCards, X } from "lucide-react";
import ChitLayout from "../../components/chit/ChitLayout";
import TrialRunChecklist from "../../components/dashboard/TrialRunChecklist";
import { useAuth } from "../../hooks/useAuth";
import { getChitCommandDashboard } from "../../services/chitDashboardService";
import { exportTrialRunReport, getTrialRunChecklist, reconcileTrialRun, resetTrialData, resumeTrialRun, startTrialRun } from "../../services/trialRunService";
import "./ChitDashboard.css";
import "./ChitCommandDashboard.css";

const KPI_ICONS=[Landmark,WalletCards,WalletCards,AlertTriangle,Landmark,Users,WalletCards];
const QUICK_ACTIONS=[[Plus,"Create Chit","/chits/ai-chit"],[FileText,"Import Chit","/chits/ai-chit/upload"],[Users,"Add Member","/chits/members"],[WalletCards,"Record Collection","/chits/collections"],[ReceiptText,"Generate Receipt","/chits/receipts"],[Target,"Run Auction","/chits/auctions"],[Sparkles,"Lucky Draw","/chits/lucky-draw"],[FileText,"Reports","/chits/reports"]];

function ChitDashboard(){
  const navigate=useNavigate();const {activeTenantContext,profile}=useAuth();const [search,setSearch]=useState("");const [aiOpen,setAiOpen]=useState(true);const [trialOpen,setTrialOpen]=useState(false);const [trial,setTrial]=useState(()=>getTrialRunChecklist(activeTenantContext));
  useEffect(()=>setTrial(getTrialRunChecklist(activeTenantContext)),[activeTenantContext]);
  const model=useMemo(()=>getChitCommandDashboard(activeTenantContext),[activeTenantContext]);const greeting=getGreeting();const maxTrend=Math.max(...model.collectionTrend.map(x=>x.value),1);const filteredActions=QUICK_ACTIONS.filter(([,label])=>label.toLowerCase().includes(search.toLowerCase()));
  const refreshTrial=(next)=>{setTrial(next);setTrialOpen(true)};const resetTrial=()=>{if(window.confirm("Reset only tenant-scoped records tagged as Internal Trial data? Real business records will remain untouched."))refreshTrial(resetTrialData(activeTenantContext))};const exportTrial=()=>{const file=exportTrialRunReport(trial);const url=URL.createObjectURL(new Blob([file.content],{type:file.mimeType}));const link=document.createElement("a");link.href=url;link.download=file.fileName;link.click();URL.revokeObjectURL(url)};
  return <ChitLayout showFloatingAI={false}>
    <div className={`apple-command ${aiOpen?"ai-open":""}`}>
      <header className="apple-topbar"><label><Search/><input aria-label="Search quick commands" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search commands"/></label><div><span><CalendarDays/>{new Date(model.generatedAt).toLocaleDateString("en-IN",{day:"numeric",month:"short",year:"numeric"})}</span><button aria-label={`${model.notifications.unreadCount} unread notifications`} onClick={()=>navigate("/chits/notifications")}><Bell/><i>{model.notifications.unreadCount}</i></button><button onClick={()=>setTrialOpen(true)}>Trial</button></div></header>
      <main className="apple-main"><section className="apple-greeting"><div><span>{greeting}</span><h1>{profile?.full_name?.split(" ")[0]||"Business owner"}, here’s your verified business position.</h1><p>{activeTenantContext?.workspace_label||"Active workspace"} · refreshed from tenant repositories</p></div><button onClick={()=>navigate("/chits/collections")}><Plus/>Record collection</button></section>
        {search&&<section className="apple-search-results" aria-live="polite"><span>Quick commands</span>{filteredActions.length?filteredActions.map(([Icon,label,route])=><button key={label} onClick={()=>navigate(route)}><Icon/>{label}<ArrowRight/></button>):<p>No matching command.</p>}</section>}
        <section className="apple-kpis" aria-label="Verified business metrics">{model.kpis.map((item,index)=>{const Icon=KPI_ICONS[index%KPI_ICONS.length];return <article key={item.label}><div><span className="apple-kpi-icon"><Icon/></span><button title={item.evidence} aria-label={`How ${item.label} is calculated`}><CircleHelp/></button></div><small>{item.label}</small><strong>{item.value}</strong><p>{item.helper||"No historical comparison available"}</p><button onClick={()=>navigate(item.route)}>How calculated?<ArrowRight/></button></article>})}</section>
        <section className="apple-quick"><header><div><span>Quick actions</span><h2>Run today’s work</h2></div></header><div>{QUICK_ACTIONS.map(([Icon,label,route])=><button key={label} onClick={()=>navigate(route)}><Icon/><span>{label}</span></button>)}</div></section>
        <div className="apple-grid"><section className="apple-panel apple-trend"><header><div><span>Collections overview</span><h2>This month’s actual postings</h2></div><strong>{formatMoney(model.monthlyCollection)}</strong></header>{model.collectionTrend.length?<div className="apple-bars" aria-label="Actual daily collection trend">{model.collectionTrend.map(x=><div key={x.date}><span style={{height:`${Math.max(x.value/maxTrend*100,4)}%`}} title={`${x.date}: ${formatMoney(x.value)}`}/><small>{x.label}</small></div>)}</div>:<Empty icon={WalletCards} title="No collection trend yet" text="Post a collection to build an evidence-backed chart."/>}</section>
          <section className="apple-panel apple-modes"><header><div><span>Collection by mode</span><h2>Actual payment totals</h2></div></header><div>{model.paymentModes.map((x,index)=><article key={x.name}><i className={`mode-${index}`}/><span>{x.name}</span><strong>{formatMoney(x.value)}</strong></article>)}</div></section>
          <section className="apple-panel apple-activity"><header><div><span>Recent activity</span><h2>What changed</h2></div></header>{model.activities.length?model.activities.map(item=><button key={item.id} onClick={()=>navigate(item.route)}><i/><span><strong>{item.title}</strong><small>{item.description}</small></span><ArrowRight/></button>):<Empty icon={FileText} title="No activity yet" text="Create a chit or add a member to begin."/>}</section>
          <section className="apple-panel apple-reminders"><header><div><span>Upcoming</span><h2>Reminders</h2></div></header>{model.reminders.length?model.reminders.map(item=><button key={item.id} onClick={()=>navigate(item.route)}><CalendarDays/><span><strong>{item.title}</strong><small>{item.type} · {item.date||"Date pending"}</small></span></button>):<Empty icon={CalendarDays} title="No reminders" text="Auction dates and pending follow-ups will appear here."/>}</section></div>
      </main>
      <aside id="chit-ai-priorities" aria-label="VARDHAN AI priorities" className={`apple-ai-panel ${aiOpen?"open":""}`}><header><div><span><Bot/>VARDHAN AI</span><button type="button" aria-label="Close AI panel" aria-expanded="true" aria-controls="chit-ai-priorities" onClick={()=>setAiOpen(false)}><X/></button></div><h2>Actions backed by your data</h2><p>Provider-independent insights from current tenant records.</p></header>{model.insights.length?model.insights.map(item=><article key={item.id}><span className={`priority-${item.priority}`}>{item.priority}</span><h3>{item.title}</h3><p>{item.reason}</p><small>Evidence: {item.evidence}</small><button onClick={()=>navigate(item.actionRoute)}>{item.safeAction}<ArrowRight/></button></article>):<Empty icon={Bot} title="No AI suggestions yet" text="Suggestions appear only when repository evidence exists."/>}<button className="apple-ask-ai" onClick={()=>navigate("/chits/ai")}><Sparkles/>Ask VARDHAN AI</button></aside>
      {!aiOpen&&<button className="apple-ai-toggle" type="button" aria-expanded="false" aria-controls="chit-ai-priorities" onClick={()=>setAiOpen(true)}><Bot/>AI</button>}
      <TrialRunChecklist model={trial} isOpen={trialOpen} onClose={()=>setTrialOpen(false)} onStepOpen={navigate} onStart={()=>refreshTrial(startTrialRun(activeTenantContext))} onResume={()=>refreshTrial(resumeTrialRun(activeTenantContext))} onReset={resetTrial} onReconcile={()=>refreshTrial({...trial,reconciliation:reconcileTrialRun(activeTenantContext)})} onExport={exportTrial}/>
    </div>
  </ChitLayout>;
}
function Empty({icon:Icon,title,text}){return <div className="apple-empty"><Icon/><strong>{title}</strong><p>{text}</p></div>}
function getGreeting(){const hour=new Date().getHours();return hour<12?"Good morning":hour<17?"Good afternoon":"Good evening"}
function formatMoney(value){return new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR",maximumFractionDigits:0}).format(Number(value||0))}
export default ChitDashboard;
