export const SECURITY_ROLES = {
  PLATFORM_OWNER: "PLATFORM_OWNER",
  SUPER_ADMIN: "SUPER_ADMIN",
  CUSTOMER_ADMIN: "CUSTOMER_ADMIN",
  MANAGER: "MANAGER",
  STAFF: "STAFF",
  ACCOUNTANT: "ACCOUNTANT",
  VIEW_ONLY: "VIEW_ONLY",
  DEMO_USER: "DEMO_USER",
};

export const SECURITY_PERMISSIONS = {
  DASHBOARD: "Dashboard",
  MEMBERS: "Members",
  GROUPS: "Groups",
  COLLECTIONS: "Collections",
  RECEIPTS: "Receipts",
  FINANCE: "Finance",
  AUCTION: "Auction",
  REPORTS: "Reports",
  SETTINGS: "Settings",
  SUPPORT: "Support",
  IMPORT: "Import",
  EXPORT: "Export",
  AI: "AI",
};

const ALL_PERMISSIONS = Object.values(SECURITY_PERMISSIONS);

const ROLE_PERMISSION_MAP = {
  [SECURITY_ROLES.PLATFORM_OWNER]: ALL_PERMISSIONS,
  [SECURITY_ROLES.SUPER_ADMIN]: ALL_PERMISSIONS,
  [SECURITY_ROLES.CUSTOMER_ADMIN]: ALL_PERMISSIONS,
  [SECURITY_ROLES.MANAGER]: [
    SECURITY_PERMISSIONS.DASHBOARD,
    SECURITY_PERMISSIONS.MEMBERS,
    SECURITY_PERMISSIONS.GROUPS,
    SECURITY_PERMISSIONS.COLLECTIONS,
    SECURITY_PERMISSIONS.RECEIPTS,
    SECURITY_PERMISSIONS.AUCTION,
    SECURITY_PERMISSIONS.REPORTS,
    SECURITY_PERMISSIONS.SUPPORT,
    SECURITY_PERMISSIONS.IMPORT,
    SECURITY_PERMISSIONS.EXPORT,
    SECURITY_PERMISSIONS.AI,
  ],
  [SECURITY_ROLES.ACCOUNTANT]: [
    SECURITY_PERMISSIONS.DASHBOARD,
    SECURITY_PERMISSIONS.COLLECTIONS,
    SECURITY_PERMISSIONS.RECEIPTS,
    SECURITY_PERMISSIONS.FINANCE,
    SECURITY_PERMISSIONS.REPORTS,
    SECURITY_PERMISSIONS.EXPORT,
  ],
  [SECURITY_ROLES.STAFF]: [
    SECURITY_PERMISSIONS.DASHBOARD,
    SECURITY_PERMISSIONS.MEMBERS,
    SECURITY_PERMISSIONS.COLLECTIONS,
    SECURITY_PERMISSIONS.RECEIPTS,
    SECURITY_PERMISSIONS.SUPPORT,
  ],
  [SECURITY_ROLES.VIEW_ONLY]: [
    SECURITY_PERMISSIONS.DASHBOARD,
    SECURITY_PERMISSIONS.MEMBERS,
    SECURITY_PERMISSIONS.GROUPS,
    SECURITY_PERMISSIONS.REPORTS,
  ],
  [SECURITY_ROLES.DEMO_USER]: [
    SECURITY_PERMISSIONS.DASHBOARD,
    SECURITY_PERMISSIONS.MEMBERS,
    SECURITY_PERMISSIONS.GROUPS,
    SECURITY_PERMISSIONS.COLLECTIONS,
    SECURITY_PERMISSIONS.REPORTS,
    SECURITY_PERMISSIONS.AI,
  ],
};

export const PermissionEngine = {
  getAllPermissions() {
    return ALL_PERMISSIONS;
  },

  buildPermissionSet(role) {
    const normalizedRole = normalizeSecurityRole(role);
    const allowed = new Set(ROLE_PERMISSION_MAP[normalizedRole] || ROLE_PERMISSION_MAP[SECURITY_ROLES.STAFF]);

    return ALL_PERMISSIONS.reduce((permissions, permission) => {
      permissions[permission] = allowed.has(permission);
      return permissions;
    }, {});
  },

  canAccess(permission, permissionSet = {}) {
    return Boolean(permissionSet[permission]);
  },
};

export function normalizeSecurityRole(role) {
  const normalized = String(role || "")
    .trim()
    .toUpperCase()
    .replace(/[^A-Z0-9]+/g, "_");

  if (normalized === "CUSTOMER_OWNER" || normalized === "ADMIN") return SECURITY_ROLES.CUSTOMER_ADMIN;
  if (normalized === "DEMO_CUSTOMER") return SECURITY_ROLES.DEMO_USER;
  return SECURITY_ROLES[normalized] || SECURITY_ROLES.STAFF;
}
